# Generated by Django 3.1.3 on 2020-11-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='categorys',
        ),
        migrations.AddField(
            model_name='counselor',
            name='tag',
            field=models.ManyToManyField(to='user.Category'),
        ),
    ]
