# Generated by Django 3.1.3 on 2020-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201124_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_counselor', models.BooleanField()),
                ('is_client', models.BooleanField()),
                ('introduction', models.CharField(max_length=255)),
                ('able_time', models.CharField(default='', max_length=255)),
                ('tag', models.ManyToManyField(to='user.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Counselor',
        ),
    ]
