# Generated by Django 3.1.3 on 2020-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201124_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(null=True, to='user.Category'),
        ),
    ]
