# Generated by Django 3.1.3 on 2020-11-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201124_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(default='진로', to='user.Category'),
        ),
    ]
