# Generated by Django 3.1.3 on 2020-11-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201124_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='able_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(null=True, to='user.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AbleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('able_from', models.CharField(max_length=50)),
                ('able_to', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
