# Generated by Django 3.1.3 on 2020-11-24 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201124_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='abletime',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abletime',
            name='concern',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abletime',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abletime',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor', to=settings.AUTH_USER_MODEL),
        ),
    ]
